FROM gcr.io/deepnote-200602/templates/deepnote
RUN sudo apt-get update -y
RUN sudo apt-get install -y openmpi-bin
RUN sudo apt-get install -y libopenmpi-dev
RUN sudo apt-get install -y build-essential
RUN pip install mpi4py
